name: condition_execution_userinput

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: 'dev'

jobs:
    deploy:
        runs-on: ubuntu-latest
        
        steps:
            - name: always run this step
              run: echo "This step always runs"

            - name: Check environment
              if: ${{ github.event.inputs.environment == 'prod' }}
              run: echo "Deploying to production"