name: condition execution

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest

        if: github.ref == 'refs/heads/main'

        steps:
            - name: Run condition
              run: echo "This is a condition execution"
            
            - name: step 1
              run: echo "This is step 1"

            - name: step 2
              if: failure()
              run: echo "Runs only when step 1 fails"