name: Environment variable AND SECRET

on: workflow_dispatch

jobs:
    variable-demo:
        runs-on: ubuntu-latest

        environment: prod

        steps:
            
            - name: print environment variable from repo
              env:
                API_URL: ${{vars.API_URL}}
                APP_MODE: ${{vars.APP_MODE}}
              run: |
                echo "api url: $API_URL"
                echo "app mode: $APP_MODE"

            - name: Get secret value
              env:
                DB_PASS: ${{secrets.DB_PASSWORD}}
              run: |
                echo "DB password length is ${#DB_PASS}"
                echo "DB password is ${DB_PASS}"

            - name: fetch secret to file
              env:
                DB_PASS: ${{secrets.DB_PASSWORD}}
              run: |
                echo "${DB_PASS}" > secret.txt
                cat secret.txt
