name: Explore git components

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        name: Build-job
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: display runner info
              run: |
                echo "Runner OS: $RUNNER_OS"
                echo "Runner Arch: $RUNNER_ARCH"





